workflows:
  flutter-app:
    name: Flutter App CI/CD
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: "3.27.1"
      xcode: "16.2"
      cocoapods: "1.15.2"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: 設定 Flutter 版本號
        script: |
          VERSION_NAME=$(grep 'version:' pubspec.yaml | awk '{print $2}' | cut -d '+' -f1)
          BUILD_NUMBER=$(git rev-list --count HEAD)
          BUILD_NAME="$VERSION_NAME(d$BUILD_NUMBER)"

          echo "Version Name: $BUILD_NAME"
          echo "Version Code: $BUILD_NUMBER"

          echo "FLUTTER_BUILD_NAME=$BUILD_NAME" >> $CM_ENV
          echo "FLUTTER_BUILD_NUMBER=$BUILD_NUMBER" >> $CM_ENV
          

      - name: 安裝 Flutter 依賴
        script: |
          flutter pub get

      - name: 構建 Android APK
        script: |
          flutter build apk --flavor dev --release

      - name: 構建 iOS
        script: |
          flutter build ios --flavor dev --release

    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/iphoneos/*.app
